version: "3.7"
services:
  web:
    # コンテナ名
    container_name: web_inslide
    # ビルドするdockerファイルが格納されたディレクトリ
    build: ./web-Inslide
    image: web_inlide
    # 正常起動後に実行するコマンド
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      # マウントするディレクトリ
      - ./web-Inslide:/workspace
    ports:
      # ホスト側のポート：コンテナ側のポート
      - 8000:8000
    env_file:
      # 環境変数に設定するファイル
      - ./web-Inslide/.env
    depends_on:
      # 接続するサービス
      - db

  db:
    container_name: db_inslide
    build: ./db-Inslide
    image: db_inslide
    volumes:
      # /var/lib/postgresql/dataにDBのデータが格納されている
      - ./db-Inslide/inslide_data:/var/lib/postgresql/data
    env_file: 
      - ./db-Inslide/.env
    ports:
      # ホスト側のポートはローカルのpsqlとバッティングするので5432以外にする
      - 5435:5432

volumes:
  inslide_data:
    external: 
      name: inslide_postgres 

  